### ISSUE TITLE
Exception in ExchangeSharp -> Not DateTime Kind

### ISSUE THREAD

**Issue by LORDofDOOM** [MachinaCore/MachinaTrader#3]
https://github.com/MachinaCore/MachinaTrader/blob/682331d0ff1d45ad25969ba3bbfb01f762b9ce73/MachinaTrader/TradeManagers/TradeManager.cs#L622

For PaperTrade I get exceptions because DateTime.MinValue don't have any DateTime Kind (should be UTC) and DateTime.MinValue as startDate is not possible on real exchanges. 

Here is the exeption:

```
System.InvalidOperationException: Unable to create unix epoch from DateTime with unspecified date time kind
   at ExchangeSharp.CryptoUtility.UnixTimestampFromDateTimeMilliseconds(DateTime dt)
   at ExchangeSharp.ExchangeBinanceAPI.OnGetCandlesAsync(String symbol, Int32 periodSeconds, Nullable`1 startDate, Nullable`1 endDate, Nullable`1 limit)
   at ExchangeSharp.ExchangeAPI.GetCandlesAsync(String symbol, Int32 periodSeconds, Nullable`1 startDate, Nullable`1 endDate, Nullable`1 limit)
   at Mynt.Core.Exchanges.BaseExchange.GetTickerHistory(String market, Period period, DateTime startDate, Nullable`1 endDate) in D:\MyntUI\Mynt.Core\Exchanges\BaseExchange.cs:line 274
```

This results in a non working selling (Papertrade).

**Comment by LORDofDOOM** [comment]
I think the error is that you use DateTime.MinValue as inititalizer, but it's not set to another DateTime if it's no simulation (e.g. Papertrade). I've add a commit that should fix this. 

Please review if it's OK

Here is my commit:

https://github.com/MachinaCore/MachinaTrader/commit/6ca2e3f1d80910915ed3f8033cc54c3646fea6bc
